### ISSUE TITLE
Crashes after keyboard interrupt

### ISSUE THREAD

**Issue by kroppt** [Chronolegionnaire/Vintage-Story-Mod-Packer#1]
1. Start the app.
2. Press Ctrl+C.
3. The app prints, "Press Enter to exit...".
4. Press enter.
5. Crash:
```
Select an option: Press Enter to exit...
Traceback (most recent call last):
  File "modpacker.py", line 258, in <module>
  File "modpacker.py", line 243, in main_menu
KeyboardInterrupt
[PYI-24580:ERROR] Failed to execute script 'modpacker' due to unhandled exception!
```

**Comment by Chronolegionnaire** [comment]
Fixed in latest push
